name: Discord Ranking

on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

jobs:
  post-ranking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Ranking Script
        run: node postRanking.js
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}